<p>Napisałeś już <?php echo $this->getPostCounter(); ?> postów</p>
<form action="<?php echo $this->getFormAction() ?>" method="post">
    <label>Firstname:</label><input type="text" name="firstname">
    <label>Lastname:</label><input type="text" name="lastname">
    <label>Content:</label> <textarea name="content"></textarea>
    <label>Date:</label><input name="sent_at" type="datetime-local">
    <input type="submit" value="Send">
</form>